name: qgis-desktop
version: "3.0.1"
confinement: strict
summary: QT GIS desktop application
description: |
  QT GIS desktop application
grade: devel

apps:
  qgis:
    command: desktop-launch qgis
    plugs:
        - x11
        - network
        - home
        - opengl

parts:
  application:
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DWITH_DESKTOP=ON
      - -DWITH_SERVER=OFF
      - -DWITH_3D=ON
      - -DBUILD_TESTING=OFF
      - -DENABLE_TESTS=OFF
    source: .
    stage-packages:
      - libc6
      - libexpat1
      - libfcgi
      - libgdal20
      - libgeos-3.5.1
      - libgsl23
      - libgslcblas0
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - liborc-0.4-0
      - libpq5
      - libproj12
      - libqca2-plugin-ossl
      - libqca-qt5-2
      - libqt53dcore5
      - libqt53dextras5
      - libqt53dinput5
      - libqt53dlogic5
      - libqt53drender5
      - libqt5concurrent5
      - libqt5keychain1
      - libqt5opengl5
      - libqt5positioning5
      - libqt5qml5
      - libqt5quick5
      - libqt5scintilla2-12v5
      - libqt5script5
      - libqt5sql5-sqlite
      - libqt5svg5
      - libqt5webkit5
      - libqwt-qt5-6
      - libspatialindex4v5
      - libspatialite7
      - libsqlite3-0
      - libxcomposite1
      - libxslt1.1
      - libzip4
      - python3
      - python3-gdal
      - python3-geolinks
      - python3-pil
      - python3-pip
      - python3-psycopg2
      - python3-pyqt5
      - python3-pyqt5.qsci
      - python3-pyqt5.qtsql
      - python3-qwt
      - python3-shapely
      - python3-sip
      - python3-sip-dev
      - python3-six
      - zlib1g
      # - xauth
      # - xfonts-100dpi
      # - xfonts-75dpi
      # - xfonts-base
      # - xfonts-scalable
    build-packages:
      - libexpat1-dev
      - libfcgi-dev
      - libgdal-dev
      - libgeos-dev
      - libgsl-dev
      - libpq-dev
      - libqca-qt5-2-dev
      - libqca-qt5-2-plugins
      - libqt5designer5
      - libqt5opengl5-dev
      - libqt5scintilla2-dev
      - libqt5sql5-sqlite
      - libqt5svg5-dev
      - libqt5webkit5-dev
      - libqt5xmlpatterns5-dev
      - libqwt-qt5-dev
      - libspatialindex-dev
      - libspatialite-dev
      - libsqlite3-dev
      - locales
      - pkg-config
      - poppler-utils
      - pyqt5-dev
      - pyqt5-dev-tools
      - pyqt5.qsci-dev
      - python3
      - python3-dev
      - python3-gdal
      - python3-geolinks
      - python3-pip
      - python3-pyqt5.qsci
      - python3-pyqt5.qtsql
      - python3-qwt
      - python3-sip
      - python3-sip-dev
      - python3-six
      - qt5keychain-dev
      - qtpositioning5-dev
      - qtscript5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - qtxmlpatterns5-dev-tools
      - xauth
      - xfonts-100dpi
      - xfonts-75dpi
      - xfonts-base
      - xfonts-scalable
      - xvfb
      #- python3-pyspatialite
    after: [desktop-qt5]
